# Cleaning dataframe
### 1. Read previous dataframe

In [27]:
import sys
import os

sys.path.append(os.path.abspath('..'))

In [28]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_pickle("../data/raw/raw_df.pkl")
df

,League,Team,Name,Age,Position,Market Value,Matches Played,Minutes,Matches Started,Goals Scored,Goals Scored (Per90),Goal Involvement,Goal Involvement (Per90),Goals at Home,Goals at Away,Expected Goals (xG),Expected Goals (xG) (Per90),Non-Penalty xG (npxG),Goals Conceded,Clean Sheets,Tackles,Tackles (Per90),Interceptions,Interceptions (Per90),Clearances,Clearances (Per90),Shots Blocked,Shots Blocked (Per90),Dribbled Past,Dribbled Past (Per90),Penalties Given Away,Penalties Given Away (Per90),Ground Duels,Ground Duels (Per90),Ground Duels Won,Ground Duels Won (Per90),Aerial Duels Won,Aerial Duels Won (Per90),Assists,Assists (Per90),Expected Assists (xA),Expected Assists (xA) (Per90),Passes,Passes (Per90),Successful Passes,Successful Passes (Per90),Pass Completion Rate,Key Passes,Key Passes (Per90),Crosses,Crosses (Per90),Successful Crosses,Successful Crosses (Per90),Cross Completion Rate,Dribbles,Dribbles (Per90),Successful Dribbles,Successful Dribbles (Per90),Dribble Success Rate,Dispossesed,Dispossesed (Per90),Offsides,Offsides (Per90),Yellow Cards,Red Cards,Total Cards,Total Cards (Per90),Cards Over 0.5,Cards Over 0.5 (Per90),Fouls Committed,Fouls Committed (Per90),Fouled Against,Fouled Against (Per90),Penalties Scored,Penalties Taken,Penalties Missed,Penalty Conversion Rate,Annual Salary,Shots Faced,Shots Faced (Per90),Saves,Saves (Per90),Save Percentage,Punches,Punches (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
0,premier-league,Manchester City,Gianluigi Donnarumma,27,Goalkeeper,€45.00m,28.0,2520.0,28.0,0.0,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,22.0,12.0,1.0,0.04,1.0,0.04,38.0,1.36,NaN,NaN,1.0,0.04,0.0,0.00,22.0,0.79,20.0,0.71,15.0,0.54,0.0,0.00,1.33,0.05,746.0,26.64,597.0,21.32,80.03%,0.0,0.00,0.0,0.00,0.0,0.00,0.00%,2,0.07,2.0,0.07,100.00%,0.0,0.00,0.0,0.00,6.0,0.0,6.0,0.21,6.0,21%,0.0,0.00,3.0,0.11,0.0,0.0,0.0,No Pens,"€18,850,000",NaN,NaN,67.0,2.39,73.63%,25.0,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,premier-league,Manchester City,James Trafford,23,Goalkeeper,€25.00m,31.0,2790.0,31.0,1.0,0.03,2.0,0.06,1.0,0.0,2.09,0.07,2.09,35.0,11.0,41.0,1.32,26.0,0.84,209.0,6.74,NaN,NaN,12.0,0.39,1.0,0.03,283.0,9.13,197.0,6.35,124.0,4.00,1.0,0.03,3.19,0.10,1279.0,41.26,1026.0,33.10,80.22%,15.0,0.48,7.0,0.23,2.0,0.06,28.57%,8,0.26,5.0,0.16,62.50%,1.0,0.03,2.0,0.06,5.0,0.0,5.0,0.16,5.0,16%,23.0,0.74,31.0,1.00,0.0,0.0,0.0,No Pens,"€9,048,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,premier-league,Manchester City,Josko Gvardiol,24,Centre-Back,€70.00m,16.0,1304.0,15.0,2.0,0.14,4.0,0.28,2.0,0.0,2.38,0.16,2.38,12.0,7.0,16.0,1.10,13.0,0.90,60.0,4.14,10.0,0.69,1.0,0.07,1.0,0.07,91.0,6.28,49.0,3.38,25.0,1.73,2.0,0.14,3.25,0.22,971.0,67.02,867.0,59.84,89.29%,5.0,0.35,2.0,0.14,1.0,0.07,50.00%,6,0.41,2.0,0.14,33.33%,3.0,0.21,0.0,0.00,2.0,0.0,2.0,0.14,2.0,12%,16.0,1.10,7.0,0.48,0.0,0.0,0.0,No Pens,"€15,080,000",123.0,2.34,NaN,NaN,NaN,NaN,NaN,11.76,17.0,1.17,5.0,0.35,12.0,0.83,29.41,8.50
4,premier-league,Manchester City,Marc Guéhi,25,Centre-Back,€65.00m,29.0,2610.0,29.0,3.0,0.10,5.0,0.17,0.0,3.0,3.74,0.13,3.74,28.0,11.0,42.0,1.45,42.0,1.45,135.0,4.66,20.0,0.69,11.0,0.38,0.0,0.00,230.0,7.93,150.0,5.17,80.0,2.76,2.0,0.07,5.38,0.19,1806.0,62.28,1606.0,55.38,88.93%,13.0,0.45,14.0,0.48,3.0,0.10,21.43%,9,0.31,4.0,0.14,44.44%,13.0,0.45,0.0,0.00,5.0,0.0,5.0,0.17,5.0,17%,18.0,0.62,27.0,0.93,0.0,0.0,0.0,No Pens,"€2,970,500",75.0,4.10,NaN,NaN,NaN,NaN,NaN,10.71,28.0,0.97,8.0,0.28,20.0,0.69,28.57,9.33
5,premier-league,Manchester City,Rúben Dias,28,Centre-Back,€60.00m,25.0,2051.0,23.0,2.0,0.09,2.0,0.09,1.0,1.0,1.98,0.09,1.98,19.0,11.0,14.0,0.61,25.0,1.10,113.0,4.96,17.0,0.75,2.0,0.09,0.0,0.00,129.0,5.66,79.0,3.47,55.0,2.41,0.0,0.00,3.81,0.17,1662.0,72.93,1551.0,68.06,93.32%,6.0,0.26,9.0,0.39,3.0,0.13,33.33%,6,0.26,3.0,0.13,50.00%,3.0,0.13,0.0,0.00,3.0,0.0,3.0,0.13,3.0,12%,14.0,0.61,9.0,0.39,0.0,0.0,0.0,No Pens,"€18,850,000",123.0,2.34,NaN,NaN,NaN,NaN,NaN,20.00,10.0,0.44,4.0,0.18,6.0,0.26,40.00,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,la-liga,Real Oviedo,Thiago Fernández,22,Left Winger,€4.50m,7.0,82.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.25,0.27,0.25,2.0,2.0,2.0,2.17,0.0,0.00,4.0,4.34,0.0,0.00,1.0,1.08,0.0,0.00,21.0,22.77,10.0,10.84,7.0,7.59,0.0,0.00,0.05,0.05,28.0,30.36,19.0,20.60,67.86%,0.0,0.00,0.0,0.00,0.0,0.00,0.00%,0,0.00,0.0,0.00,0.00%,2.0,2.17,1.0,1.08,1.0,0.0,1.0,1.10,1.0,14%,3.0,3.25,2.0,2.17,0.0,0.0,0.0,No Pens,"€754,000",123.0,4.10,NaN,NaN,NaN,NaN,NaN,33.33,6.0,0.27,1.0,0.07,5.0,0.33,16.67,0.00
1015,la-liga,Real Oviedo,Ilyas Chaira,25,Left Winger,€4.00m,29.0,1939.0,24.0,4.0,0.19,6.0,0.28,3.0,1.0,7.49,0.35,7.49,26.0,9.0,40.0,1.86,5.0,0.23,10.0,0.46,4.0,0.19,22.0,1.02,0.0,0.00,286.0,13.27,102.0,4.73,15.0,0.70,2.0,0.09,2.73,0.13,529.0,24.55,443.0,20.56,83.74%,14.0,0.65,55.0,2.55,9.0,0.42,16.36%,84,3.90,24.0,1.11,28.57%,31.0,1.44,16.0,0.74,3.0,1.0,4.0,0.19,2.0,7%,47.0,2.18,25.0,1.16,0.0,0.0,0.0,No Pens,"€1,175,000",67.0,3.19,NaN,NaN,NaN,NaN,NaN,33.33,6.0,0.40,1.0,0.22,5.0,0.33,16.67,3.00
1016,la-liga,Real Oviedo,Ovie Ejaria,28,Left Winger,€500k,7.0,179.0,2.0,0.0,0.00,0.0,0.00,0.0,0.0,0.21,0.11,0.21,2.0,2.0,4.0,2.03,2.0,1.02,3.0,1.53,0.0,0.00,4.0,2.03,0.0,0.00,33.0,16.78,15.0,7.63,5.0,2.54,0.0,0.00,0.20,0.10,94.0,47.80,82.0,41.69,87.23%,1.0,0.51,0.0,0.00,0.0,0.00,0.00%,3,1.53,2.0,1.02,66.67%,5.0,2.54,1.0,0.51,1.0,0.0,1.0,0.50,1.0,14%,3.0,1.53,5.0,2.54,0.0,0.0,0.0,No Pens,"€840,000",67.0,4.10,NaN,NaN,NaN,NaN,NaN,33.33,6.0,0.27,1.0,0.07,5.0,0.33,83.33,3.00
1018,la-liga,Real Oviedo,Federico Viñas,27,Centre-Forward,€4.00m,23.0,275.0,1.0,2.0,0.65,3.0,0.98,1.0,1.0,2.30,0.69,2.30,4.0,6.0,8.0,2.42,4.0,1.21,7.0,2.11,2.0,0.60,4.0,1.21,0.0,0.00,47.0,14.19,17.0,5.13,2.0,0.60,1.0,0.33,0.86,0.26,103.0,31.11,75.0,22.65,72.82%,3.0,0.91,14.0,4.23,0.0,0.00,0.00%,11,3.32,2.0,0.60,18.18%,3.0,0.91,2.0,0.60,3.0,0.0,3.0,0.98,3.0,13%,9.0,2.72,5.0,1.51,0.0,0.0,0.0,No Pens,"€10,857,600",67.0,4.19,NaN,NaN,NaN,NaN,NaN,5.88,6.0,0.82,1.0,0.22,5.0,0.41,33.33,17.00
1019,la-liga,Real Oviedo,Thiago Borbas,24,Centre-Forward,€4.00m,7.0,82.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.25,0.27,0.25,2.0,2.0,2.0,2.17,0.0,0.00,4.0,4.34,0.0,0.00,1.0,1.08,0.0,0.00,21.0,22.77,10.0,10.84,7.0,7.59,0.0,0.00,0.05,0.05,28.0,30.36,19.0,20.60,67.86%,0.0,0.00,0.0,0.00,0.0,0.00,0.00%,0,0.00,0.0,0.00,0.00%,2.0,2.17,1.0,1.08,1.0,0.0,1.0,1.10,1.0,14%,3.0,3.25,2.0,2.17,0.0,0.0,0.0,No Pens,"€2,639,000",67.0,4.19,NaN,NaN,NaN,NaN,NaN,0.00,23.0,0.82,6.0,0.20,11.0,0.56,21.74,4.25

### 2. Strings to Numeric

Importing utils functions with dynamic reloading

In [29]:
import importlib
import scripts.utils
importlib.reload(scripts.utils)

In [30]:
from scripts.utils import *
# dir(utils)

Convert Money Columns

In [31]:
money_cols = [
    "Market Value",
    "Annual Salary"
]

for col in money_cols:
    df[col] = df[col].apply(money_to_int)

Convert Percent Columns

In [32]:
percent_cols = [
    "Pass Completion Rate",
    "Dribble Success Rate",
    "Cross Completion Rate",
    "Save Percentage",
    "Cards Over 0.5 (Per90)",
    "Penalty Conversion Rate",
    "Shot Accuracy",
]

for col in percent_cols:
    df[col] = df[col].apply(percent_to_float)

Convert "No" strings to numeric 0

In [33]:
df["Penalty Conversion Rate"] = df["Penalty Conversion Rate"].replace("No Pens", np.nan)
df["Dribbles"] = df["Dribbles"].replace("Not Recorded", np.nan)

### 3. Data Type Conversion

Columns that should be Integers

In [34]:
int_cols = [
    "Age",
    "Matches Played",
    "Minutes",
    "Matches Started",
    "Goals Scored",
    "Goal Involvement",
    "Goals at Home",
    "Goals at Away",
    "Goals Conceded",
    "Clean Sheets",
    "Tackles",
    "Interceptions",
    "Clearances",
    "Shots Blocked",
    "Dribbled Past",
    "Penalties Given Away",
    "Ground Duels",
    "Ground Duels Won",
    "Aerial Duels Won",
    "Assists",
    "Passes",
    "Successful Passes",
    "Key Passes",
    "Crosses",
    "Successful Crosses",
    "Dribbles",
    "Successful Dribbles",
    "Dispossesed",
    "Offsides",
    "Yellow Cards",
    "Red Cards",
    "Total Cards",
    "Cards Over 0.5",
    "Fouls Committed",
    "Fouled Against",
    "Penalties Scored",
    "Penalties Taken",
    "Penalties Missed",
    "Shots Faced",
    "Saves",
    "Punches",
    "Shots Taken",
    "Shots On Target",
    "Shots Off Target"
]

Test the columns for non-numeric data

In [35]:
bad_values = {}

for col in int_cols:
    coerced = pd.to_numeric(df[col], errors="coerce")
    mask = coerced.isna() & df[col].notna()

    bad_values[col] = df.loc[mask, col].unique()

# bad_values
# df.loc[df["Dribbles"].eq("Not Recorded"), ["Name", "Position", "Dribbles"]]

Convert to Int64

In [36]:
df[int_cols] = df[int_cols].astype("Int64")

### 3. Split according to Position

In [37]:
df_gk = df[df["Position"] == "Goalkeeper"]
df_outfield = df[df["Position"] != "Goalkeeper"]

### 4. Remove Useless Columns

In [38]:
useless_gk_cols = df_gk.columns[
    df_gk.apply(lambda col: ((col == 0) | (col.isna())).all())
]

useless_gk_cols

Index(['Shots Blocked', 'Shots Blocked (Per90)', 'Penalties Scored',
       'Penalties Taken', 'Penalties Missed', 'Penalty Conversion Rate',
       'Shots Faced', 'Shots Faced (Per90)', 'Shot Conversion Rate',
       'Shots Taken', 'Shots Taken (Per90)', 'Shots On Target',
       'Shots On Target (Per90)', 'Shots Off Target',
       'Shots Off Target (Per90)', 'Shot Accuracy', 'Shots Per Goal Scored'],
      dtype='str')

In [39]:
cols_to_drop = [
    'Goals Scored',
    'Goals Scored (Per90)',
    'Goal Involvement',
    'Goal Involvement (Per90)',
    'Goals at Home',
    'Goals at Away',
    'Expected Goals (xG)',
    'Expected Goals (xG) (Per90)',
    'Non-Penalty xG (npxG)'
]

df_gk = df_gk.drop(columns=cols_to_drop, errors='ignore')

In [40]:
useless_outfield_cols = [
    "Saves",
    "Saves (Per90)",
    "Save Percentage",
    "Punches",
    "Punches (Per90)",
    "Penalty Conversion Rate"
]

useless_outfield_cols

['Saves',
 'Saves (Per90)',
 'Save Percentage',
 'Punches',
 'Punches (Per90)',
 'Penalty Conversion Rate']

In [41]:
df_gk = df_gk.drop(columns=useless_gk_cols)
df_outfield = df_outfield.drop(columns=useless_outfield_cols)

### 5. Drop NaN records

In [42]:
df_outfield[df_outfield["Dribbles"].isna()]

,League,Team,Name,Age,Position,Market Value,Matches Played,Minutes,Matches Started,Goals Scored,Goals Scored (Per90),Goal Involvement,Goal Involvement (Per90),Goals at Home,Goals at Away,Expected Goals (xG),Expected Goals (xG) (Per90),Non-Penalty xG (npxG),Goals Conceded,Clean Sheets,Tackles,Tackles (Per90),Interceptions,Interceptions (Per90),Clearances,Clearances (Per90),Shots Blocked,Shots Blocked (Per90),Dribbled Past,Dribbled Past (Per90),Penalties Given Away,Penalties Given Away (Per90),Ground Duels,Ground Duels (Per90),Ground Duels Won,Ground Duels Won (Per90),Aerial Duels Won,Aerial Duels Won (Per90),Assists,Assists (Per90),Expected Assists (xA),Expected Assists (xA) (Per90),Passes,Passes (Per90),Successful Passes,Successful Passes (Per90),Pass Completion Rate,Key Passes,Key Passes (Per90),Crosses,Crosses (Per90),Successful Crosses,Successful Crosses (Per90),Cross Completion Rate,Dribbles,Dribbles (Per90),Successful Dribbles,Successful Dribbles (Per90),Dribble Success Rate,Dispossesed,Dispossesed (Per90),Offsides,Offsides (Per90),Yellow Cards,Red Cards,Total Cards,Total Cards (Per90),Cards Over 0.5,Cards Over 0.5 (Per90),Fouls Committed,Fouls Committed (Per90),Fouled Against,Fouled Against (Per90),Penalties Scored,Penalties Taken,Penalties Missed,Annual Salary,Shots Faced,Shots Faced (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
216,premier-league,Nottingham Forest,Chris Wood,34,Centre-Forward,6000000.0,1,46,<NA>,1,1.96,1,1.96,1,0,NaN,NaN,NaN,0,1,<NA>,NaN,<NA>,NaN,<NA>,NaN,1,0.60,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0.00,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,0,0,0,0.00,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0,0,2350000.0,67,4.19,0.0,5,0.75,6,0.25,18,0.72,13.33,12.0
317,premier-league,Brighton & Hove Albion,Solly March,31,Right Winger,2000000.0,1,4,<NA>,0,0.00,0,0.00,0,0,NaN,NaN,NaN,0,0,<NA>,NaN,<NA>,NaN,<NA>,NaN,3,0.00,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0.00,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,0,0,0,0.00,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0,0,8911500.0,85,3.40,0.0,31,0.78,12,0.06,3,0.35,40.00,0.0
370,premier-league,Everton FC,Tyler Dibling,20,Right Winger,22000000.0,1,2,<NA>,0,0.00,0,0.00,0,0,NaN,NaN,NaN,0,1,<NA>,NaN,<NA>,NaN,<NA>,NaN,1,0.00,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0.00,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,0,0,0,0.00,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0,0,1040000.0,85,3.40,20.0,31,0.67,1,0.11,19,0.35,38.71,0.0
376,premier-league,Fulham FC,Joachim Andersen,29,Centre-Back,25000000.0,29,2562,<NA>,0,0.00,1,0.04,0,0,NaN,NaN,NaN,37,6,<NA>,NaN,<NA>,NaN,<NA>,NaN,1,1.47,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,1,0.04,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,7,0,7,0.25,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0,0,2600000.0,75,4.10,25.0,15,0.00,1,0.07,1,0.50,30.00,0.0
413,premier-league,Sunderland AFC,Chris Rigg,18,Attacking Midfield,25000000.0,1,46,<NA>,1,1.96,1,1.96,1,0,NaN,NaN,NaN,0,1,<NA>,NaN,<NA>,NaN,<NA>,NaN,5,0.06,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0.00,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,<NA>,NaN,0,0,0,0.00,<NA>,NaN,<NA>,NaN,<NA>,NaN,0,0,0,4901000.0,106,4.00,0.0,7,0.48,8,0.26,6,0.23,14.29,15.0

In [43]:
df_outfield = df_outfield.dropna(subset=["Dribbles"])

In [44]:
df_gk[['Saves', 'Punches']].isna().sum()


df_gk = df_gk.dropna(subset=['Saves', 'Punches'])


df_gk[['Saves', 'Punches']].isna().sum()

Saves      0
Punches    0
dtype: int64

### 6. Validation

NA Check

In [45]:
pd.DataFrame(df_gk.isna().sum()).T

,League,Team,Name,Age,Position,Market Value,Matches Played,Minutes,Matches Started,Goals Conceded,Clean Sheets,Tackles,Tackles (Per90),Interceptions,Interceptions (Per90),Clearances,Clearances (Per90),Dribbled Past,Dribbled Past (Per90),Penalties Given Away,Penalties Given Away (Per90),Ground Duels,Ground Duels (Per90),Ground Duels Won,Ground Duels Won (Per90),Aerial Duels Won,Aerial Duels Won (Per90),Assists,Assists (Per90),Expected Assists (xA),Expected Assists (xA) (Per90),Passes,Passes (Per90),Successful Passes,Successful Passes (Per90),Pass Completion Rate,Key Passes,Key Passes (Per90),Crosses,Crosses (Per90),Successful Crosses,Successful Crosses (Per90),Cross Completion Rate,Dribbles,Dribbles (Per90),Successful Dribbles,Successful Dribbles (Per90),Dribble Success Rate,Dispossesed,Dispossesed (Per90),Offsides,Offsides (Per90),Yellow Cards,Red Cards,Total Cards,Total Cards (Per90),Cards Over 0.5,Cards Over 0.5 (Per90),Fouls Committed,Fouls Committed (Per90),Fouled Against,Fouled Against (Per90),Annual Salary,Saves,Saves (Per90),Save Percentage,Punches,Punches (Per90)
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [46]:
pd.DataFrame(df_outfield.isna().sum()).T

,League,Team,Name,Age,Position,Market Value,Matches Played,Minutes,Matches Started,Goals Scored,Goals Scored (Per90),Goal Involvement,Goal Involvement (Per90),Goals at Home,Goals at Away,Expected Goals (xG),Expected Goals (xG) (Per90),Non-Penalty xG (npxG),Goals Conceded,Clean Sheets,Tackles,Tackles (Per90),Interceptions,Interceptions (Per90),Clearances,Clearances (Per90),Shots Blocked,Shots Blocked (Per90),Dribbled Past,Dribbled Past (Per90),Penalties Given Away,Penalties Given Away (Per90),Ground Duels,Ground Duels (Per90),Ground Duels Won,Ground Duels Won (Per90),Aerial Duels Won,Aerial Duels Won (Per90),Assists,Assists (Per90),Expected Assists (xA),Expected Assists (xA) (Per90),Passes,Passes (Per90),Successful Passes,Successful Passes (Per90),Pass Completion Rate,Key Passes,Key Passes (Per90),Crosses,Crosses (Per90),Successful Crosses,Successful Crosses (Per90),Cross Completion Rate,Dribbles,Dribbles (Per90),Successful Dribbles,Successful Dribbles (Per90),Dribble Success Rate,Dispossesed,Dispossesed (Per90),Offsides,Offsides (Per90),Yellow Cards,Red Cards,Total Cards,Total Cards (Per90),Cards Over 0.5,Cards Over 0.5 (Per90),Fouls Committed,Fouls Committed (Per90),Fouled Against,Fouled Against (Per90),Penalties Scored,Penalties Taken,Penalties Missed,Annual Salary,Shots Faced,Shots Faced (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Data Types

In [47]:
pd.DataFrame(df.dtypes).T

,League,Team,Name,Age,Position,Market Value,Matches Played,Minutes,Matches Started,Goals Scored,Goals Scored (Per90),Goal Involvement,Goal Involvement (Per90),Goals at Home,Goals at Away,Expected Goals (xG),Expected Goals (xG) (Per90),Non-Penalty xG (npxG),Goals Conceded,Clean Sheets,Tackles,Tackles (Per90),Interceptions,Interceptions (Per90),Clearances,Clearances (Per90),Shots Blocked,Shots Blocked (Per90),Dribbled Past,Dribbled Past (Per90),Penalties Given Away,Penalties Given Away (Per90),Ground Duels,Ground Duels (Per90),Ground Duels Won,Ground Duels Won (Per90),Aerial Duels Won,Aerial Duels Won (Per90),Assists,Assists (Per90),Expected Assists (xA),Expected Assists (xA) (Per90),Passes,Passes (Per90),Successful Passes,Successful Passes (Per90),Pass Completion Rate,Key Passes,Key Passes (Per90),Crosses,Crosses (Per90),Successful Crosses,Successful Crosses (Per90),Cross Completion Rate,Dribbles,Dribbles (Per90),Successful Dribbles,Successful Dribbles (Per90),Dribble Success Rate,Dispossesed,Dispossesed (Per90),Offsides,Offsides (Per90),Yellow Cards,Red Cards,Total Cards,Total Cards (Per90),Cards Over 0.5,Cards Over 0.5 (Per90),Fouls Committed,Fouls Committed (Per90),Fouled Against,Fouled Against (Per90),Penalties Scored,Penalties Taken,Penalties Missed,Penalty Conversion Rate,Annual Salary,Shots Faced,Shots Faced (Per90),Saves,Saves (Per90),Save Percentage,Punches,Punches (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
0,str,str,str,Int64,str,float64,Int64,Int64,Int64,Int64,float64,Int64,float64,Int64,Int64,float64,float64,float64,Int64,Int64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,float64,float64,Int64,float64,Int64,float64,float64,Int64,float64,Int64,float64,Int64,float64,float64,Int64,float64,Int64,float64,float64,Int64,float64,Int64,float64,Int64,Int64,Int64,float64,Int64,float64,Int64,float64,Int64,float64,Int64,Int64,Int64,str,float64,Int64,float64,Int64,float64,float64,Int64,float64,float64,Int64,float64,Int64,float64,Int64,float64,float64,float64

Duplicated Records/Columns

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df.columns[df.columns.duplicated()]

Index([], dtype='str')

### 7. Output dataframe for next step

In [50]:
df_gk.to_pickle("../data/clean/clean_df_gk.pkl")
df_outfield.to_pickle("../data/clean/clean_df_outfield.pkl")


df_gk.to_csv("../data/clean/clean_df_gk.csv")
df_outfield.to_csv("../data/clean/clean_df_outfield.csv")

In [51]:
df_outfield

,League,Team,Name,Age,Position,Market Value,Matches Played,Minutes,Matches Started,Goals Scored,Goals Scored (Per90),Goal Involvement,Goal Involvement (Per90),Goals at Home,Goals at Away,Expected Goals (xG),Expected Goals (xG) (Per90),Non-Penalty xG (npxG),Goals Conceded,Clean Sheets,Tackles,Tackles (Per90),Interceptions,Interceptions (Per90),Clearances,Clearances (Per90),Shots Blocked,Shots Blocked (Per90),Dribbled Past,Dribbled Past (Per90),Penalties Given Away,Penalties Given Away (Per90),Ground Duels,Ground Duels (Per90),Ground Duels Won,Ground Duels Won (Per90),Aerial Duels Won,Aerial Duels Won (Per90),Assists,Assists (Per90),Expected Assists (xA),Expected Assists (xA) (Per90),Passes,Passes (Per90),Successful Passes,Successful Passes (Per90),Pass Completion Rate,Key Passes,Key Passes (Per90),Crosses,Crosses (Per90),Successful Crosses,Successful Crosses (Per90),Cross Completion Rate,Dribbles,Dribbles (Per90),Successful Dribbles,Successful Dribbles (Per90),Dribble Success Rate,Dispossesed,Dispossesed (Per90),Offsides,Offsides (Per90),Yellow Cards,Red Cards,Total Cards,Total Cards (Per90),Cards Over 0.5,Cards Over 0.5 (Per90),Fouls Committed,Fouls Committed (Per90),Fouled Against,Fouled Against (Per90),Penalties Scored,Penalties Taken,Penalties Missed,Annual Salary,Shots Faced,Shots Faced (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
3,premier-league,Manchester City,Josko Gvardiol,24,Centre-Back,70000000.0,16,1304,15,2,0.14,4,0.28,2,0,2.38,0.16,2.38,12,7,16,1.10,13,0.90,60,4.14,10,0.69,1,0.07,1,0.07,91,6.28,49,3.38,25,1.73,2,0.14,3.25,0.22,971,67.02,867,59.84,0.8929,5,0.35,2,0.14,1,0.07,0.5000,6,0.41,2,0.14,0.3333,3,0.21,0,0.00,2,0,2,0.14,2,0.12,16,1.10,7,0.48,0,0,0,15080000.0,123,2.34,11.76,17,1.17,5,0.35,12,0.83,29.41,8.50
4,premier-league,Manchester City,Marc Guéhi,25,Centre-Back,65000000.0,29,2610,29,3,0.10,5,0.17,0,3,3.74,0.13,3.74,28,11,42,1.45,42,1.45,135,4.66,20,0.69,11,0.38,0,0.00,230,7.93,150,5.17,80,2.76,2,0.07,5.38,0.19,1806,62.28,1606,55.38,0.8893,13,0.45,14,0.48,3,0.10,0.2143,9,0.31,4,0.14,0.4444,13,0.45,0,0.00,5,0,5,0.17,5,0.17,18,0.62,27,0.93,0,0,0,2970500.0,75,4.10,10.71,28,0.97,8,0.28,20,0.69,28.57,9.33
5,premier-league,Manchester City,Rúben Dias,28,Centre-Back,60000000.0,25,2051,23,2,0.09,2,0.09,1,1,1.98,0.09,1.98,19,11,14,0.61,25,1.10,113,4.96,17,0.75,2,0.09,0,0.00,129,5.66,79,3.47,55,2.41,0,0.00,3.81,0.17,1662,72.93,1551,68.06,0.9332,6,0.26,9,0.39,3,0.13,0.3333,6,0.26,3,0.13,0.5000,3,0.13,0,0.00,3,0,3,0.13,3,0.12,14,0.61,9,0.39,0,0,0,18850000.0,123,2.34,20.00,10,0.44,4,0.18,6,0.26,40.00,5.00
6,premier-league,Manchester City,Abdukodir Khusanov,22,Centre-Back,35000000.0,16,979,10,0,0.00,0,0.00,0,0,0.15,0.01,0.15,7,6,21,1.93,20,1.84,38,3.49,5,0.46,5,0.46,0,0.00,67,6.16,36,3.31,6,0.55,0,0.00,1.42,0.13,705,64.81,645,59.30,0.9149,4,0.37,1,0.09,1,0.09,1.0000,6,0.55,4,0.37,0.6667,2,0.18,0,0.00,2,0,2,0.18,2,0.12,11,1.01,5,0.46,0,0,0,3770000.0,75,4.10,0.00,3,0.28,0,0.00,3,0.28,0.00,0.00
7,premier-league,Manchester City,John Stones,31,Centre-Back,15000000.0,7,352,4,0,0.00,0,0.00,0,0,0.00,0.00,0.00,7,1,0,0.00,2,0.51,13,3.31,4,1.02,2,0.51,0,0.00,15,3.82,11,2.80,9,2.29,0,0.00,0.45,0.11,257,65.52,238,60.68,0.9261,1,0.25,4,1.02,0,0.00,0.0000,2,0.51,2,0.51,1.0000,1,0.25,0,0.00,0,0,0,0.00,0,0.00,0,0.00,0,0.00,0,0,0,18850000.0,75,4.10,0.00,0,0.00,0,0.00,0,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,la-liga,Real Oviedo,Thiago Fernández,22,Left Winger,4500000.0,7,82,0,0,0.00,0,0.00,0,0,0.25,0.27,0.25,2,2,2,2.17,0,0.00,4,4.34,0,0.00,1,1.08,0,0.00,21,22.77,10,10.84,7,7.59,0,0.00,0.05,0.05,28,30.36,19,20.60,0.6786,0,0.00,0,0.00,0,0.00,0.0000,0,0.00,0,0.00,0.0000,2,2.17,1,1.08,1,0,1,1.10,1,0.14,3,3.25,2,2.17,0,0,0,754000.0,123,4.10,33.33,6,0.27,1,0.07,5,0.33,16.67,0.00
1015,la-liga,Real Oviedo,Ilyas Chaira,25,Left Winger,4000000.0,29,1939,24,4,0.19,6,0.28,3,1,7.49,0.35,7.49,26,9,40,1.86,5,0.23,10,0.46,4,0.19,22,1.02,0,0.00,286,13.27,102,4.73,15,0.70,2,0.09,2.73,0.13,529,24.55,443,20.56,0.8374,14,0.65,55,2.55,9,0.42,0.1636,84,3.90,24,1.11,0.2857,31,1.44,16,0.74,3,1,4,0.19,2,0.07,47,2.18,25,1.16,0,0,0,1175000.0,67,3.19,33.33,6,0.40,1,0.22,5,0.33,16.67,3.00
1016,la-liga,Real Oviedo,Ovie Ejaria,28,Left Winger,500000.0,7,179,2,0,0.00,0,0.00,0,0,0.21,0.11,0.21,2,2,4,2.03,2,1.02,3,1.53,0,0.00,4,2.03,0,0.00,33,16.78,15,7.63,5,2.54,0,0.00,0.20,0.10,94,47.80,82,41.69,0.8723,1,0.51,0,0.00,0,0.00,0.0000,3,1.53,2,1.02,0.6667,5,2.54,1,0.51,1,0,1,0.50,1,0.14,3,1.53,5,2.54,0,0,0,840000.0,67,4.10,33.33,6,0.27,1,0.07,5,0.33,83.33,3.00
1018,la-liga,Real Oviedo,Federico Viñas,27,Centre-Forward,4000000.0,23,275,1,2,0.65,3,0.98,1,1,2.30,0.69,2.30,4,6,8,2.42,4,1.21,7,2.11,2,0.60,4,1.21,0,0.00,47,14.19,17,5.13,2,0.60,1,0.33,0.86,0.26,103,31.11,75,22.65,0.7282,3,0.91,14,4.23,0,0.00,0.0000,11,3.32,2,0.60,0.1818,3,0.91,2,0.60,3,0,3,0.98,3,0.13,9,2.72,5,1.51,0,0,0,10857600.0,67,4.19,5.88,6,0.82,1,0.22,5,0.41,33.33,17.00
1019,la-liga,Real Oviedo,Thiago Borbas,24,Centre-Forward,4000000.0,7,82,0,0,0.00,0,0.00,0,0,0.25,0.27,0.25,2,2,2,2.17,0,0.00,4,4.34,0,0.00,1,1.08,0,0.00,21,22.77,10,10.84,7,7.59,0,0.00,0.05,0.05,28,30.36,19,20.60,0.6786,0,0.00,0,0.00,0,0.00,0.0000,0,0.00,0,0.00,0.0000,2,2.17,1,1.08,1,0,1,1.10,1,0.14,3,3.25,2,2.17,0,0,0,2639000.0,67,4.19,0.00,23,0.82,6,0.20,11,0.56,21.74,4.25